### ISSUE TITLE
Resistors in schematics have no value specified

### ISSUE THREAD

**Issue by geriljaSA** [prynth/prynth#1]
Hi.

The resistors and capacitors also in the schematic have no value (that I could find)

Can you please add to the bill of materials or the schematics the component values?

Thanks!

**Comment by ifranco** [comment]
Hi. The resistors don't have specific values because you can use different values.

The resistors you find on the multiplexer boards are pull down resistors, so you should only populate them if you will be using switches instead of variable resistors. In that case, anything between 1K and 10K should be OK.

The capacitor is there mostly for good measure, in case you have big voltage drops. This is  conditioned by the application and shouldn't be necessary, unless you run into any instability when using sensors. In that case you will have to try different values and test.

The only resistor that needs a specific value is the midi out, which isn't really documented, since it doesn't follow the midi specification (3.3V instead of 5V). I tested it briefly but I'm not sure if it is reliable enough. If it is I will write about that feature in the future, at which point I will add the resistance value (by the way, so you know, it should be 47ohms, to have traditional MIDI on +3.3V).

Hope that helps.

**Comment by geriljaSA** [comment]
Thanks! That helps a lot. I did not understand why the variable resistors seemed to need a pulldown resistor. But makes sense when you say they are only needed for switches. I just finished putting it together on prototyping board with one multiplexer and some variable resistors for a quick test... and it works 👍 Look forward to play more with this!

Thanks for the good work!

**Comment by ifranco** [comment]
I would love to know what you're doing with it with Prynth.
My contacts are on the webpage (https://prynth.github.io/).

Thanks
